### ISSUE TITLE
ModuleNotFoundError: No module named 'argo' when running assemble

### ISSUE THREAD

**Issue by fridex** [thoth-station/s2i-thoth#100]
**Describe the bug**

```
STEP 8: RUN /usr/libexec/s2i/assemble
/tmp/src ~
Traceback (most recent call last):
  File "/usr/local/bin/thamos", line 5, in <module>
    from thamos.cli import cli
  File "/usr/local/lib/python3.8/site-packages/thamos/cli.py", line 38, in <module>
    from thoth.python import Project
  File "/usr/local/lib/python3.8/site-packages/thoth/python/__init__.py", line 20, in <module>
    from .digests_fetcher import DigestsFetcherBase
  File "/usr/local/lib/python3.8/site-packages/thoth/python/digests_fetcher.py", line 23, in <module>
    from .source import Source
  File "/usr/local/lib/python3.8/site-packages/thoth/python/source.py", line 40, in <module>
    from thoth.common.helpers import parse_datetime
  File "/usr/local/lib/python3.8/site-packages/thoth/common/__init__.py", line 36, in <module>
    from .workflows import Workflow
  File "/usr/local/lib/python3.8/site-packages/thoth/common/workflows.py", line 35, in <module>
    from argo.workflows import client
ModuleNotFoundError: No module named 'argo'
```

**Comment by fridex** [comment]
This is caused by thoth-common which includes argo. Unfortunately, more recent argo=4 causes issues, we need to pin it to <4.
