### ISSUE TITLE
S2I sometimes hangs during build on OpenShift

### ISSUE THREAD

**Issue by CermakM** [thoth-station/s2i-thoth#48]
**Describe the bug**
A build sometimes hangs. Unable to find the reason or provide a reproducer, but it only happens during resource-expensive builds, i.e.: https://github.com/CermakM/jupyter-notebooks/tree/experimental/scipy-notebook

**Environment variables used for s2i configuration**

```
ENABLE_PIPENV=1
THOTH_ERROR_FALLBACK=1
```

**Expected behavior**
The build is completed successfully or fails.

**Actual behavior**
The build hangs.

**Build Log**

<details><summary>Log</summary>

```
Using docker-registry.default.svc:5000/macermak-thoth-dev/s2i-minimal-notebook@sha256:74ed8de638f4430c0f4baeaba7c0f07b7d601468f7de5f12c13beb599a14d31d as the s2i builder image
--
  | + set -eo pipefail
  | + /opt/app-root/builder/assemble
  | + set -eo pipefail
  | + APP_ROOT=/opt/app-root
  | + /usr/libexec/s2i/assemble
  | /tmp/src ~
  | >>> Performing hardware and software discovery...
  | 2020-03-18 07:40:54,141 [16] INFO     thamos: Configuration file already present, no action performed in non-interactive mode
  | >>> Thoth's configuration file after hardware and software discovery:
  | host: khemenu.thoth-station.ninja
  | tls_verify: true
  | requirements_format: pipenv
  | runtime_environments:
  | - name: ubi8
  | operating_system:
  | name: ubi
  | version: "8"
  | python_version: "3.6"
  | recommendation_type: latest
  | managers:
  | - name: update
  | configuration:
  | labels: [bot]
  | - name: info
  | - name: version
  | configuration:
  | maintainers:
  | - fridex
  | - goern
  | - cermakm
  | assignees:
  | - sesheta
  | labels: [bot]
  | changelog_file: true
  | >>> Asking Thoth for advise...
  | 2020-03-18 07:40:55,044 [20] INFO     thamos.lib: Performing static analysis of sources to gather library usage
  | 2020-03-18 07:40:55,044 [20] WARNING  thamos.lib: No library usage was aggregated - no Python sources found
  | 2020-03-18 07:40:55,214 [20] INFO     thamos.lib: Successfully submitted advise analysis 'adviser-8c5c2788-f973f1c4' to 'https://khemenu.thoth-station.ninja/api/v1'
  | 2020-03-18 07:40:55,242 [20] CRITICAL root: Traceback (most recent call last):
  | File "/opt/app-root/bin/thamos", line 8, in <module>
  | sys.exit(cli())
  | File "/opt/app-root/lib/python3.7/site-packages/click/core.py", line 829, in __call__
  | return self.main(*args, **kwargs)
  | File "/opt/app-root/lib/python3.7/site-packages/click/core.py", line 782, in main
  | rv = self.invoke(ctx)
  | File "/opt/app-root/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
  | return _process_result(sub_ctx.command.invoke(sub_ctx))
  | File "/opt/app-root/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
  | return ctx.invoke(self.callback, **ctx.params)
  | File "/opt/app-root/lib/python3.7/site-packages/click/core.py", line 610, in invoke
  | return callback(*args, **kwargs)
  | File "/opt/app-root/lib/python3.7/site-packages/thamos/cli.py", line 372, in advise
  | no_static_analysis=no_static_analysis,
  | File "/opt/app-root/lib/python3.7/site-packages/thamos/lib.py", line 81, in wrapper
  | result = func(api_client, *args, **kwargs)
  | File "/opt/app-root/lib/python3.7/site-packages/thamos/lib.py", line 322, in advise
  | _wait_for_analysis(api_instance.get_advise_python_status, response.analysis_id)
  | File "/opt/app-root/lib/python3.7/site-packages/thamos/lib.py", line 108, in _wait_for_analysis
  | response = status_func(analysis_id)
  | File "/opt/app-root/lib/python3.7/site-packages/thamos/swagger_client/thoth/advise_api.py", line 239, in get_advise_python_status
  | (data) = self.get_advise_python_status_with_http_info(analysis_id, **kwargs)  # noqa: E501
  | File "/opt/app-root/lib/python3.7/site-packages/thamos/swagger_client/thoth/advise_api.py", line 312, in get_advise_python_status_with_http_info
  | collection_formats=collection_formats)
  | File "/opt/app-root/lib/python3.7/site-packages/thamos/swagger_client/api_client.py", line 321, in call_api
  | _preload_content, _request_timeout)
  | File "/opt/app-root/lib/python3.7/site-packages/thamos/swagger_client/api_client.py", line 152, in __call_api
  | _request_timeout=_request_timeout)
  | File "/opt/app-root/lib/python3.7/site-packages/thamos/swagger_client/api_client.py", line 342, in request
  | headers=headers)
  | File "/opt/app-root/lib/python3.7/site-packages/thamos/swagger_client/rest.py", line 237, in GET
  | query_params=query_params)
  | File "/opt/app-root/lib/python3.7/site-packages/thamos/swagger_client/rest.py", line 227, in request
  | raise ApiException(http_resp=r)
  | thamos.swagger_client.rest.ApiException: (404)
  | Reason: NOT FOUND
  | HTTP response headers: HTTPHeaderDict({'Server': 'gunicorn/20.0.4', 'Date': 'Wed, 18 Mar 2020 07:40:55 GMT', 'Content-Type': 'application/json', 'Content-Length': '159', 'X-Thoth-Version': '0.6.0-dev', 'Access-Control-Allow-Origin': '*', 'Set-Cookie': 'ae5b4faaab1fe6375d62dbc3b1efaf0d=dfd2c6d26ac834625f834de6d21d9681; path=/; HttpOnly; Secure', 'Cache-control': 'private'})
  | HTTP response body: {
  | "error": "Requested status for analysis 'adviser-8c5c2788-f973f1c4' was not found",
  | "parameters": {
  | "analysis_id": "adviser-8c5c2788-f973f1c4"
  | }
  | }
```
</details>

**Comment by fridex** [comment]
I treid to run s2i locally, it looks like dependencies are correctly installed. Can you try disabling advises completely to see if Thoth is the issue maker here?

```THOTH_ADVISE=0```

**Comment by CermakM** [comment]
Haven't hit the issue yet with `THOTH_ADVISE=0`

**Comment by fridex** [comment]
Is this happening on `v0.8.0` as well as on `v0.11.3`?

**Comment by CermakM** [comment]
Didn't test `THOTH_ADVISE=0` with `v0.8.0`, but the issue was happening with either of these.

**Comment by fridex** [comment]
> Didn't test `THOTH_ADVISE=0` with `v0.8.0`

Can you test it with this configuration? It would narrow down more to the issue maker.

**Comment by CermakM** [comment]
Will give i a shot once I am back up with the Workflows, should be able to do it tomorrow.

**Comment by CermakM** [comment]
Unable to reproduce with 0.8.0 as I am not able to use it for the build, currently, due to some changes to the image (like missing `rsync` command). Can do a work around it and install the dep manually, if it is crucial for the debugging of this issue, tho.

**Comment by fridex** [comment]
Closing this issue, feel free to reopen if the issue persists.
